services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    ports:
      - "4173:4173"
